services:
  baro-payment:
    build:
      context: .
      dockerfile: docker/baro-payment/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CONFIG_IMPORT=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=baro-kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://baro-mysql:3306/${MYSQL_DATABASE_PAYMENT:-baropayment}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - PAYMENT_TOSS_SECRET_KEY=
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_S3_BUCKET_NAME=
    volumes: []
