# AI 모듈
# 추천, 챗봇, 제철

services:
  baro-ai:
    image: ${DOCKER_REGISTRY:-ghcr.io/do-develop-space}/baro-ai:${IMAGE_TAG:-latest}
    container_name: baro-ai
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JAVA_OPTS=-Xms64m -Xmx128m
    volumes:
      - ${S3_MOUNT_PATH:-/mnt/s3}:/mnt/s3:rw
    restart: unless-stopped
    networks:
      - baro-network

networks:
  baro-network:
    name: be_baro-network  # 네트워크 이름 명시적으로 지정
    external: true

