services:
  baro-order:
    build:
      context: .
      dockerfile: docker/baro-order/Dockerfile
    environment:
      - BUYER_SERVICE_URL=http://baro-buyer:8082
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CONFIG_IMPORT=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=baro-kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://baro-mysql:3306/${MYSQL_DATABASE_ORDER:-baroorder}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - AWS_ACCESS_KEY=
      - AWS_SECRET_KEY=
      - AWS_S3_BUCKET_NAME=
    volumes: []
