apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baro-prod

resources:
  - deployment.yaml
  - cronjob.yaml
  - service.yaml

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app: baro-settlement
      component: app

images:
  - name: ghcr.io/do-develop-space/baro-settlement
    newTag: latest

